# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0cddbe1c128510369bff538b6a03f76478ddc229ff0d7e06e6fd21be118be3a90d47c1df2e58082cd5d7ebd88d01d349d2851c5dd732e8e8cdc01f1bb89a61d

test:
  secret_key_base: 669babaf700247f24c9c25d0ed9f809ad73ed0f4ff0d09274b2cb11b7d67c1372463cc1045297d8673a242539210870459509a380d970a3d8567093de2c58f91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
